GET https://localhost:3443/api/

###
GET https://localhost:3443/api/users
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM2OTk4MjMyLCJleHAiOjE2MzcwODQ2MzJ9.nQll57Nt2n06dVpk9e9rfTiPyzUBH4zrTQXJLq4S3B4"
}


###
GET https://localhost:3443/api/userInfo
content-type: application/json

{
    "email": "user1@test.com"
}

###
GET https://localhost:3443/api/userInfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoidXNlcjNAdGVzdC5jb20ifSwiaWF0IjoxNjM3NTkxNzczLCJleHAiOjE2Mzc2NzgxNzN9.C-s8RZ3UiUmr5vVx1WEYUZnbIjErZtA7IvlYuKATq3s
content-type: application/json

{
    "email": "user3@test.com"
}


###
POST https://localhost:3443/api/auth/login
content-type: application/json

{
    "email": "user3@test.com",
    "password": "user3password"
}

###
POST  https://localhost:3443/api/auth/registration
content-type: application/json

{
    "email": "user1@test.com",
    "password": "user8password"    
}


###
POST https://localhost:3443/api/auth/refresh
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM2OTI1OTQ2LCJleHAiOjE2Mzc0NTE1NDZ9.LCvP4WusxDMoFfkHENMItgXr_bH7XTUALLTMLRo9vxE"
}


###
POST  https://localhost:3443/api/isEmailFree
content-type: application/json

{
    "email": "user13@test.com" 
}
