GET http://localhost:3001/api/

###
GET http://localhost:3001/api/users
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM2OTk4MjMyLCJleHAiOjE2MzcwODQ2MzJ9.nQll57Nt2n06dVpk9e9rfTiPyzUBH4zrTQXJLq4S3B4"
}


###
GET http://localhost:3001/api/userInfo
content-type: application/json

{
    "email": "user1@test.com"
}

###
GET http://localhost:3001/api/userInfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoidXNlcjNAdGVzdC5jb20ifSwiaWF0IjoxNjM3Nzk0MDcxLCJleHAiOjE2Mzc4ODA0NzF9.q6oUqLmRpJTXs8f67bmTeaY6CqHH-G_WCfwDvTyt8Xs
content-type: application/json

{
    "email": "user3@test.com"
}


###
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "email": "user3@test.com",
    "password": "user3password"
}

###
POST  http://localhost:3001/api/auth/registration
content-type: application/json

{
    "email": "user5@test.com",
    "password": "user5password"    
}


###
POST http://localhost:3001/api/auth/refresh
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM2OTI1OTQ2LCJleHAiOjE2Mzc0NTE1NDZ9.LCvP4WusxDMoFfkHENMItgXr_bH7XTUALLTMLRo9vxE"
}


###
POST  http://localhost:3001/api/isEmailFree
content-type: application/json

{
    "email": "user13@test.com" 
}


### TODO: walidacja 
GET  http://localhost:3001/api/profiles 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjo0LCJlbWFpbCI6ImFhYUBhYWEifSwiaWF0IjoxNjM4NjI0MDgzLCJleHAiOjE2Mzg3MTA0ODN9.mOQqY8h-PdnAY5BTDjtK69xLNZPgF_Q3A2M8Uh9VD7g
content-type: application/json

{
    "email": "user3@test.com"
}

###
POST  http://localhost:3001/api/profiles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImVtYWlsIjoidXNlcjNAdGVzdC5jb20ifSwiaWF0IjoxNjM3Nzk0MDcxLCJleHAiOjE2Mzc4ODA0NzF9.q6oUqLmRpJTXs8f67bmTeaY6CqHH-G_WCfwDvTyt8Xs
content-type: application/json

{
    "email": "user1@test.com",
    "name": "name3",
    "avatar": null,
    "description": "description3"
}

###
POST   http://localhost:3001/api/sets/allUserSets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjozLCJlbWFpbCI6InVzZXIzQHRlc3QuY29tIn0sImlhdCI6MTYzODc5Nzc0NCwiZXhwIjoxNjM4ODg0MTQ0fQ.Xz0wyLGE67cmTBQt2ndfL5FBA6Fj7hwxXF9whRCG3Jo
content-type: application/json





###
GET   http://localhost:3001/api/sets/set
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjozLCJlbWFpbCI6InVzZXIzQHRlc3QuY29tIn0sImlhdCI6MTYzODYxNzkwMSwiZXhwIjoxNjM4NzA0MzAxfQ.bQM-cV-h2p0DKqQioCF054b1pppTumzanrRk5Mn_3Rw
content-type: application/json

{
    "id": 3,
    "email": "user3@test.com"
}

###
Post   http://localhost:3001/api/sets/set
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjozLCJlbWFpbCI6InVzZXIzQHRlc3QuY29tIn0sImlhdCI6MTYzODMxNDQ4MiwiZXhwIjoxNjM4NDAwODgyfQ.pFg3h9_MPiy3V-yc3-pDlPgi54Qjf3erg2JwT4Pv__s
content-type: application/json

{
    "id": 3,
    "email": "user3@test.com",
    "setTitle": "setTitle3",
    "setDescription": null,
    "setPortion": null
}

###
Post   http://localhost:3001/api/sets/set
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjozLCJlbWFpbCI6InVzZXIzQHRlc3QuY29tIn0sImlhdCI6MTYzODMxNDQ4MiwiZXhwIjoxNjM4NDAwODgyfQ.pFg3h9_MPiy3V-yc3-pDlPgi54Qjf3erg2JwT4Pv__s
content-type: application/json

{
    "email": "user3@test.com",
    "setTitle": "setTitle5",
    "setDescription": null
}

###
Post   http://localhost:3001/api/sets/setFlashcards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjozLCJlbWFpbCI6InVzZXIzQHRlc3QuY29tIn0sImlhdCI6MTYzODQwMTE3MCwiZXhwIjoxNjM4NDg3NTcwfQ.pLcC8r5fFm60acKvcIjYT_rvjbUaewNbJq7arTXAA5E
content-type: application/json

{
    "email": "user3@test.com",
    "setId": 3,
    "setTitle": "setTitle9",
    "setDescription": null,
    "setPortion": null,
    "Flashcards":[
        {
            "id": 110,
            "front": "frontAA1",
            "back": "backAA1"
        },
        {
            "front": "frontBB2",
            "back": "backB"
        },
        {
            "front": "frontCC3",
            "back": "backC"
        }
    ]

}


###
Post   http://localhost:3001/api/sets/setFlashcards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjozLCJlbWFpbCI6InVzZXIzQHRlc3QuY29tIn0sImlhdCI6MTYzODU1MTMwMywiZXhwIjoxNjM4NjM3NzAzfQ.tAXaQtyxT6ouM8k8lOfaWXsDiNltqudb6URxpwouHJU
content-type: application/json

{
    "email": "user3@test.com",
    "setTitle": "setTitle9",
    "setDescription": null,
    "setPortion": null,
    "Flashcards":[
        {
            "front": "frontAA12",
            "back": "backAA12"
        },
        {
            "front": "frontBB2",
            "back": "backB"
        },
        {
            "front": "frontCC3",
            "back": "backC"
        }
    ]

}

###
Post   http://localhost:3001/api/sets/setFlashcardsNoJWT
content-type: application/json

{
    "email": "user3@test.com",
    "setTitle": "setTitle91",
    "setDescription": null,
    "Flashcards":[
        {
            "front": "frontAA12",
            "back": "backAA12"
        },
        {
            "front": "frontBB2",
            "back": "backB"
        },
        {
            "front": "frontCC3",
            "back": "backC"
        }
    ]

}





###
POST   http://localhost:3001/api/flashcards/flashcardsToLearn
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjozLCJlbWFpbCI6InVzZXIzQHRlc3QuY29tIn0sImlhdCI6MTYzODU1MTMwMywiZXhwIjoxNjM4NjM3NzAzfQ.tAXaQtyxT6ouM8k8lOfaWXsDiNltqudb6URxpwouHJU
content-type: application/json

{
    "email": "user3@test.com",
    "set_id": 3

}



###
POST    http://localhost:3001/api/flashcards/flashcardsToLearnNoJWT
content-type: application/json

{
    "set_id": 3

}

###
POST   http://localhost:3001/api/flashcards/flashcardPlusOrZero
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjozLCJlbWFpbCI6InVzZXIzQHRlc3QuY29tIn0sImlhdCI6MTYzODg4MzI5NCwiZXhwIjoxNjM4OTY5Njk0fQ.5L7wIDLnn1Hg543ZRiyDuRMXL6UV7m_BokbsVjQGpLQ
content-type: application/json

{
    "flashcardId": 20,
    "ifCorrect": false
}

###
POST   http://localhost:3001/api/flashcards/flashcardPlusOrZeroNoJWT
content-type: application/json

{
    "flashcardId": 4,
    "ifCorrect": true
}

###
POST   http://localhost:3001/api/flashcards/flashcardPlusOrZeroNoJWT
content-type: application/json

{
    "flashcardId": 4,
    "ifCorrect": false
}


###
DELETE   http://localhost:3001/api/sets/setFlashcardsDelete/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjozLCJlbWFpbCI6InVzZXIzQHRlc3QuY29tIn0sImlhdCI6MTYzODg4MzI5NCwiZXhwIjoxNjM4OTY5Njk0fQ.5L7wIDLnn1Hg543ZRiyDuRMXL6UV7m_BokbsVjQGpLQ

###
PUT http://localhost:3001/api/profiles/name/1
content-type: application/json

{
    "name": "name"
}

###
PUT http://localhost:3001/api/profiles/avatar/1
content-type: application/json

{
    "avatar": "avatar"
}


###
PUT http://localhost:3001/api/profiles/description/1
content-type: application/json

{
    "description": "description"
}

###
POST http://localhost:3001/api/auth/password
content-type: application/json

{
    "email": "user3@test.com",
    "password": "user1password"
}

###
POST http://localhost:3001/api/auth/login
content-type: application/json

{
    "email": "user3@test.com",
    "password": "user1password"
}

###
GET   http://localhost:3001/api/sets/setStatistics/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjozLCJlbWFpbCI6InVzZXIzQHRlc3QuY29tIn0sImlhdCI6MTYzODg4MzI5NCwiZXhwIjoxNjM4OTY5Njk0fQ.5L7wIDLnn1Hg543ZRiyDuRMXL6UV7m_BokbsVjQGpLQ
